// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { accessToken, create, create2, create3, delete_, delete2, delete3, deleteMe, link, list, list2, live, logout, logoutEverywhere, type Options, read, read2, readMe, ready, recover, refresh, reset, signup, testToken, update, update2, updateMe, updateMyPassword } from '../sdk.gen';
import type { AccessTokenData, AccessTokenError, AccessTokenResponse, Create2Data, Create2Error, Create2Response, Create3Data, Create3Error, Create3Response, CreateData, CreateError, CreateResponse, Delete2Data, Delete2Error, Delete2Response, Delete3Data, Delete3Error, Delete3Response, DeleteData, DeleteError, DeleteMeData, DeleteMeError, DeleteMeResponse, DeleteResponse, LinkData, LinkError, LinkResponse, List2Data, List2Error, List2Response, ListData, ListError, ListResponse, LiveData, LiveResponse, LogoutData, LogoutEverywhereData, LogoutEverywhereError, LogoutEverywhereResponse, LogoutResponse, Read2Data, Read2Error, Read2Response, ReadData, ReadError, ReadMeData, ReadMeError, ReadMeResponse, ReadResponse, ReadyData, ReadyError, ReadyResponse, RecoverData, RecoverError, RecoverResponse, RefreshData, RefreshError, RefreshResponse, ResetData, ResetError, ResetResponse, SignupData, SignupError, SignupResponse, TestTokenData, TestTokenError, TestTokenResponse, Update2Data, Update2Error, Update2Response, UpdateData, UpdateError, UpdateMeData, UpdateMeError, UpdateMeResponse, UpdateMyPasswordData, UpdateMyPasswordError, UpdateMyPasswordResponse, UpdateResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listQueryKey = (options?: Options<ListData>) => createQueryKey('list', options);

/**
 * List items
 *
 * Your own items, or every item when you are a superuser.
 */
export const listOptions = (options?: Options<ListData>) => queryOptions<ListResponse, ListError, ListResponse, ReturnType<typeof listQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await list({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listQueryKey(options)
});

/**
 * Create an item
 *
 * Owned by whoever creates it.
 */
export const createMutation = (options?: Partial<Options<CreateData>>): UseMutationOptions<CreateResponse, CreateError, Options<CreateData>> => {
    const mutationOptions: UseMutationOptions<CreateResponse, CreateError, Options<CreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await create({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete an item
 */
export const deleteMutation = (options?: Partial<Options<DeleteData>>): UseMutationOptions<DeleteResponse, DeleteError, Options<DeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteResponse, DeleteError, Options<DeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await delete_({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readQueryKey = (options: Options<ReadData>) => createQueryKey('read', options);

/**
 * Read an item
 *
 * Someone else's item reads as missing rather than forbidden, so that guessing identifiers
 * cannot confirm which ones exist.
 */
export const readOptions = (options: Options<ReadData>) => queryOptions<ReadResponse, ReadError, ReadResponse, ReturnType<typeof readQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await read({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readQueryKey(options)
});

/**
 * Update an item
 *
 * Every field is optional; anything left out keeps its current value.
 */
export const updateMutation = (options?: Partial<Options<UpdateData>>): UseMutationOptions<UpdateResponse, UpdateError, Options<UpdateData>> => {
    const mutationOptions: UseMutationOptions<UpdateResponse, UpdateError, Options<UpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await update({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Sign in
 *
 * Exchanges an email and password for a token pair.
 */
export const accessTokenMutation = (options?: Partial<Options<AccessTokenData>>): UseMutationOptions<AccessTokenResponse, AccessTokenError, Options<AccessTokenData>> => {
    const mutationOptions: UseMutationOptions<AccessTokenResponse, AccessTokenError, Options<AccessTokenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await accessToken({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Sign out
 *
 * Ends the session belonging to the given refresh token. Unknown tokens succeed quietly:
 * signing out should never fail, and saying which tokens exist would leak information.
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Sign out everywhere
 *
 * Ends every session the caller has, on every device.
 */
export const logoutEverywhereMutation = (options?: Partial<Options<LogoutEverywhereData>>): UseMutationOptions<LogoutEverywhereResponse, LogoutEverywhereError, Options<LogoutEverywhereData>> => {
    const mutationOptions: UseMutationOptions<LogoutEverywhereResponse, LogoutEverywhereError, Options<LogoutEverywhereData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logoutEverywhere({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Refresh a session
 *
 * Exchanges a refresh token for a new pair, invalidating the one presented. A stolen token
 * is therefore good for at most one refresh, and the theft shows up as the real client
 * being signed out.
 */
export const refreshMutation = (options?: Partial<Options<RefreshData>>): UseMutationOptions<RefreshResponse, RefreshError, Options<RefreshData>> => {
    const mutationOptions: UseMutationOptions<RefreshResponse, RefreshError, Options<RefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Test an access token
 *
 * Confirms an access token is valid and returns who it belongs to.
 */
export const testTokenMutation = (options?: Partial<Options<TestTokenData>>): UseMutationOptions<TestTokenResponse, TestTokenError, Options<TestTokenData>> => {
    const mutationOptions: UseMutationOptions<TestTokenResponse, TestTokenError, Options<TestTokenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await testToken({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Request a password reset
 *
 * Emails a single-use link that expires. Always answers the same way, whether or not the
 * address is registered, so that this cannot be used to find out who has an account.
 */
export const recoverMutation = (options?: Partial<Options<RecoverData>>): UseMutationOptions<RecoverResponse, RecoverError, Options<RecoverData>> => {
    const mutationOptions: UseMutationOptions<RecoverResponse, RecoverError, Options<RecoverData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recover({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reset a password
 *
 * Consumes the token from the emailed link and ends every session that account had.
 */
export const resetMutation = (options?: Partial<Options<ResetData>>): UseMutationOptions<ResetResponse, ResetError, Options<ResetData>> => {
    const mutationOptions: UseMutationOptions<ResetResponse, ResetError, Options<ResetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reset({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a file
 */
export const delete2Mutation = (options?: Partial<Options<Delete2Data>>): UseMutationOptions<Delete2Response, Delete2Error, Options<Delete2Data>> => {
    const mutationOptions: UseMutationOptions<Delete2Response, Delete2Error, Options<Delete2Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await delete2({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Start an upload
 *
 * Answers with a URL to `PUT` the file to. The file goes straight to storage rather than
 * through the API, so its size is limited by the bucket rather than by this server.
 */
export const create2Mutation = (options?: Partial<Options<Create2Data>>): UseMutationOptions<Create2Response, Create2Error, Options<Create2Data>> => {
    const mutationOptions: UseMutationOptions<Create2Response, Create2Error, Options<Create2Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await create2({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Get a download link
 *
 * Works only for your own files, so a key guessed or copied from somewhere else is a 404
 * rather than a way to read another account's uploads.
 */
export const linkMutation = (options?: Partial<Options<LinkData>>): UseMutationOptions<LinkResponse, LinkError, Options<LinkData>> => {
    const mutationOptions: UseMutationOptions<LinkResponse, LinkError, Options<LinkData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await link({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const list2QueryKey = (options?: Options<List2Data>) => createQueryKey('list2', options);

/**
 * List users
 *
 * Superusers only.
 */
export const list2Options = (options?: Options<List2Data>) => queryOptions<List2Response, List2Error, List2Response, ReturnType<typeof list2QueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await list2({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: list2QueryKey(options)
});

/**
 * Create a user
 *
 * Sets any combination of fields, including privileges. Superusers only.
 */
export const create3Mutation = (options?: Partial<Options<Create3Data>>): UseMutationOptions<Create3Response, Create3Error, Options<Create3Data>> => {
    const mutationOptions: UseMutationOptions<Create3Response, Create3Error, Options<Create3Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await create3({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Close your own account
 *
 * Superusers cannot, since deleting the last administrator would leave no way back in.
 */
export const deleteMeMutation = (options?: Partial<Options<DeleteMeData>>): UseMutationOptions<DeleteMeResponse, DeleteMeError, Options<DeleteMeData>> => {
    const mutationOptions: UseMutationOptions<DeleteMeResponse, DeleteMeError, Options<DeleteMeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readMeQueryKey = (options?: Options<ReadMeData>) => createQueryKey('readMe', options);

/**
 * Read your own account
 */
export const readMeOptions = (options?: Options<ReadMeData>) => queryOptions<ReadMeResponse, ReadMeError, ReadMeResponse, ReturnType<typeof readMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readMeQueryKey(options)
});

/**
 * Update your own account
 *
 * Every field is optional; anything left out keeps its current value.
 */
export const updateMeMutation = (options?: Partial<Options<UpdateMeData>>): UseMutationOptions<UpdateMeResponse, UpdateMeError, Options<UpdateMeData>> => {
    const mutationOptions: UseMutationOptions<UpdateMeResponse, UpdateMeError, Options<UpdateMeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Change your own password
 *
 * Requires the current password, and ends every other session on success.
 */
export const updateMyPasswordMutation = (options?: Partial<Options<UpdateMyPasswordData>>): UseMutationOptions<UpdateMyPasswordResponse, UpdateMyPasswordError, Options<UpdateMyPasswordData>> => {
    const mutationOptions: UseMutationOptions<UpdateMyPasswordResponse, UpdateMyPasswordError, Options<UpdateMyPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateMyPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register
 *
 * Open to anyone. The resulting account is always an ordinary active user, whatever the
 * request body asks for.
 */
export const signupMutation = (options?: Partial<Options<SignupData>>): UseMutationOptions<SignupResponse, SignupError, Options<SignupData>> => {
    const mutationOptions: UseMutationOptions<SignupResponse, SignupError, Options<SignupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await signup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a user
 *
 * Superusers only, and never yourself. Their items and sessions go with them.
 */
export const delete3Mutation = (options?: Partial<Options<Delete3Data>>): UseMutationOptions<Delete3Response, Delete3Error, Options<Delete3Data>> => {
    const mutationOptions: UseMutationOptions<Delete3Response, Delete3Error, Options<Delete3Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await delete3({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const read2QueryKey = (options: Options<Read2Data>) => createQueryKey('read2', options);

/**
 * Read a user
 *
 * Anyone may read themselves; only superusers may read anyone else.
 */
export const read2Options = (options: Options<Read2Data>) => queryOptions<Read2Response, Read2Error, Read2Response, ReturnType<typeof read2QueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await read2({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: read2QueryKey(options)
});

/**
 * Update a user
 *
 * Including their password and privileges. Superusers only. Setting a password ends every
 * session that user has.
 */
export const update2Mutation = (options?: Partial<Options<Update2Data>>): UseMutationOptions<Update2Response, Update2Error, Options<Update2Data>> => {
    const mutationOptions: UseMutationOptions<Update2Response, Update2Error, Options<Update2Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await update2({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const liveQueryKey = (options?: Options<LiveData>) => createQueryKey('live', options);

/**
 * Liveness probe
 *
 * Reports that the process is up. Deliberately touches nothing else, so a database blip
 * cannot convince an orchestrator to restart a perfectly healthy process.
 */
export const liveOptions = (options?: Options<LiveData>) => queryOptions<LiveResponse, DefaultError, LiveResponse, ReturnType<typeof liveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await live({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: liveQueryKey(options)
});

export const readyQueryKey = (options?: Options<ReadyData>) => createQueryKey('ready', options);

/**
 * Readiness probe
 *
 * Reports that the process can actually serve traffic, which means reaching the database.
 */
export const readyOptions = (options?: Options<ReadyData>) => queryOptions<ReadyResponse, ReadyError, ReadyResponse, ReturnType<typeof readyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ready({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readyQueryKey(options)
});
