// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AccessTokenData, AccessTokenErrors, AccessTokenResponses, Create2Data, Create2Errors, Create2Responses, Create3Data, Create3Errors, Create3Responses, CreateData, CreateErrors, CreateResponses, Delete2Data, Delete2Errors, Delete2Responses, Delete3Data, Delete3Errors, Delete3Responses, DeleteData, DeleteErrors, DeleteMeData, DeleteMeErrors, DeleteMeResponses, DeleteResponses, LinkData, LinkErrors, LinkResponses, List2Data, List2Errors, List2Responses, ListData, ListErrors, ListResponses, LiveData, LiveResponses, LogoutData, LogoutEverywhereData, LogoutEverywhereErrors, LogoutEverywhereResponses, LogoutResponses, Read2Data, Read2Errors, Read2Responses, ReadData, ReadErrors, ReadMeData, ReadMeErrors, ReadMeResponses, ReadResponses, ReadyData, ReadyErrors, ReadyResponses, RecoverData, RecoverErrors, RecoverResponses, RefreshData, RefreshErrors, RefreshResponses, ResetData, ResetErrors, ResetResponses, SignupData, SignupErrors, SignupResponses, TestTokenData, TestTokenErrors, TestTokenResponses, Update2Data, Update2Errors, Update2Responses, UpdateData, UpdateErrors, UpdateMeData, UpdateMeErrors, UpdateMeResponses, UpdateMyPasswordData, UpdateMyPasswordErrors, UpdateMyPasswordResponses, UpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List items
 *
 * Your own items, or every item when you are a superuser.
 */
export const list = <ThrowOnError extends boolean = false>(options?: Options<ListData, ThrowOnError>): RequestResult<ListResponses, ListErrors, ThrowOnError> => (options?.client ?? client).get<ListResponses, ListErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items',
    ...options
});

/**
 * Create an item
 *
 * Owned by whoever creates it.
 */
export const create = <ThrowOnError extends boolean = false>(options: Options<CreateData, ThrowOnError>): RequestResult<CreateResponses, CreateErrors, ThrowOnError> => (options.client ?? client).post<CreateResponses, CreateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an item
 */
export const delete_ = <ThrowOnError extends boolean = false>(options: Options<DeleteData, ThrowOnError>): RequestResult<DeleteResponses, DeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteResponses, DeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/{id}',
    ...options
});

/**
 * Read an item
 *
 * Someone else's item reads as missing rather than forbidden, so that guessing identifiers
 * cannot confirm which ones exist.
 */
export const read = <ThrowOnError extends boolean = false>(options: Options<ReadData, ThrowOnError>): RequestResult<ReadResponses, ReadErrors, ThrowOnError> => (options.client ?? client).get<ReadResponses, ReadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/{id}',
    ...options
});

/**
 * Update an item
 *
 * Every field is optional; anything left out keeps its current value.
 */
export const update = <ThrowOnError extends boolean = false>(options: Options<UpdateData, ThrowOnError>): RequestResult<UpdateResponses, UpdateErrors, ThrowOnError> => (options.client ?? client).patch<UpdateResponses, UpdateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Sign in
 *
 * Exchanges an email and password for a token pair.
 */
export const accessToken = <ThrowOnError extends boolean = false>(options: Options<AccessTokenData, ThrowOnError>): RequestResult<AccessTokenResponses, AccessTokenErrors, ThrowOnError> => (options.client ?? client).post<AccessTokenResponses, AccessTokenErrors, ThrowOnError>({
    url: '/api/v1/login/access-token',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Sign out
 *
 * Ends the session belonging to the given refresh token. Unknown tokens succeed quietly:
 * signing out should never fail, and saying which tokens exist would leak information.
 */
export const logout = <ThrowOnError extends boolean = false>(options: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    url: '/api/v1/login/logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Sign out everywhere
 *
 * Ends every session the caller has, on every device.
 */
export const logoutEverywhere = <ThrowOnError extends boolean = false>(options?: Options<LogoutEverywhereData, ThrowOnError>): RequestResult<LogoutEverywhereResponses, LogoutEverywhereErrors, ThrowOnError> => (options?.client ?? client).post<LogoutEverywhereResponses, LogoutEverywhereErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/login/logout-everywhere',
    ...options
});

/**
 * Refresh a session
 *
 * Exchanges a refresh token for a new pair, invalidating the one presented. A stolen token
 * is therefore good for at most one refresh, and the theft shows up as the real client
 * being signed out.
 */
export const refresh = <ThrowOnError extends boolean = false>(options: Options<RefreshData, ThrowOnError>): RequestResult<RefreshResponses, RefreshErrors, ThrowOnError> => (options.client ?? client).post<RefreshResponses, RefreshErrors, ThrowOnError>({
    url: '/api/v1/login/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Test an access token
 *
 * Confirms an access token is valid and returns who it belongs to.
 */
export const testToken = <ThrowOnError extends boolean = false>(options?: Options<TestTokenData, ThrowOnError>): RequestResult<TestTokenResponses, TestTokenErrors, ThrowOnError> => (options?.client ?? client).post<TestTokenResponses, TestTokenErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/login/test-token',
    ...options
});

/**
 * Request a password reset
 *
 * Emails a single-use link that expires. Always answers the same way, whether or not the
 * address is registered, so that this cannot be used to find out who has an account.
 */
export const recover = <ThrowOnError extends boolean = false>(options: Options<RecoverData, ThrowOnError>): RequestResult<RecoverResponses, RecoverErrors, ThrowOnError> => (options.client ?? client).post<RecoverResponses, RecoverErrors, ThrowOnError>({
    url: '/api/v1/password/recover',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset a password
 *
 * Consumes the token from the emailed link and ends every session that account had.
 */
export const reset = <ThrowOnError extends boolean = false>(options: Options<ResetData, ThrowOnError>): RequestResult<ResetResponses, ResetErrors, ThrowOnError> => (options.client ?? client).post<ResetResponses, ResetErrors, ThrowOnError>({
    url: '/api/v1/password/reset',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a file
 */
export const delete2 = <ThrowOnError extends boolean = false>(options: Options<Delete2Data, ThrowOnError>): RequestResult<Delete2Responses, Delete2Errors, ThrowOnError> => (options.client ?? client).delete<Delete2Responses, Delete2Errors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/uploads',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start an upload
 *
 * Answers with a URL to `PUT` the file to. The file goes straight to storage rather than
 * through the API, so its size is limited by the bucket rather than by this server.
 */
export const create2 = <ThrowOnError extends boolean = false>(options: Options<Create2Data, ThrowOnError>): RequestResult<Create2Responses, Create2Errors, ThrowOnError> => (options.client ?? client).post<Create2Responses, Create2Errors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/uploads',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a download link
 *
 * Works only for your own files, so a key guessed or copied from somewhere else is a 404
 * rather than a way to read another account's uploads.
 */
export const link = <ThrowOnError extends boolean = false>(options: Options<LinkData, ThrowOnError>): RequestResult<LinkResponses, LinkErrors, ThrowOnError> => (options.client ?? client).post<LinkResponses, LinkErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/uploads/link',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List users
 *
 * Superusers only.
 */
export const list2 = <ThrowOnError extends boolean = false>(options?: Options<List2Data, ThrowOnError>): RequestResult<List2Responses, List2Errors, ThrowOnError> => (options?.client ?? client).get<List2Responses, List2Errors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users',
    ...options
});

/**
 * Create a user
 *
 * Sets any combination of fields, including privileges. Superusers only.
 */
export const create3 = <ThrowOnError extends boolean = false>(options: Options<Create3Data, ThrowOnError>): RequestResult<Create3Responses, Create3Errors, ThrowOnError> => (options.client ?? client).post<Create3Responses, Create3Errors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Close your own account
 *
 * Superusers cannot, since deleting the last administrator would leave no way back in.
 */
export const deleteMe = <ThrowOnError extends boolean = false>(options?: Options<DeleteMeData, ThrowOnError>): RequestResult<DeleteMeResponses, DeleteMeErrors, ThrowOnError> => (options?.client ?? client).delete<DeleteMeResponses, DeleteMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options
});

/**
 * Read your own account
 */
export const readMe = <ThrowOnError extends boolean = false>(options?: Options<ReadMeData, ThrowOnError>): RequestResult<ReadMeResponses, ReadMeErrors, ThrowOnError> => (options?.client ?? client).get<ReadMeResponses, ReadMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options
});

/**
 * Update your own account
 *
 * Every field is optional; anything left out keeps its current value.
 */
export const updateMe = <ThrowOnError extends boolean = false>(options: Options<UpdateMeData, ThrowOnError>): RequestResult<UpdateMeResponses, UpdateMeErrors, ThrowOnError> => (options.client ?? client).patch<UpdateMeResponses, UpdateMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change your own password
 *
 * Requires the current password, and ends every other session on success.
 */
export const updateMyPassword = <ThrowOnError extends boolean = false>(options: Options<UpdateMyPasswordData, ThrowOnError>): RequestResult<UpdateMyPasswordResponses, UpdateMyPasswordErrors, ThrowOnError> => (options.client ?? client).patch<UpdateMyPasswordResponses, UpdateMyPasswordErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register
 *
 * Open to anyone. The resulting account is always an ordinary active user, whatever the
 * request body asks for.
 */
export const signup = <ThrowOnError extends boolean = false>(options: Options<SignupData, ThrowOnError>): RequestResult<SignupResponses, SignupErrors, ThrowOnError> => (options.client ?? client).post<SignupResponses, SignupErrors, ThrowOnError>({
    url: '/api/v1/users/signup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a user
 *
 * Superusers only, and never yourself. Their items and sessions go with them.
 */
export const delete3 = <ThrowOnError extends boolean = false>(options: Options<Delete3Data, ThrowOnError>): RequestResult<Delete3Responses, Delete3Errors, ThrowOnError> => (options.client ?? client).delete<Delete3Responses, Delete3Errors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{id}',
    ...options
});

/**
 * Read a user
 *
 * Anyone may read themselves; only superusers may read anyone else.
 */
export const read2 = <ThrowOnError extends boolean = false>(options: Options<Read2Data, ThrowOnError>): RequestResult<Read2Responses, Read2Errors, ThrowOnError> => (options.client ?? client).get<Read2Responses, Read2Errors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{id}',
    ...options
});

/**
 * Update a user
 *
 * Including their password and privileges. Superusers only. Setting a password ends every
 * session that user has.
 */
export const update2 = <ThrowOnError extends boolean = false>(options: Options<Update2Data, ThrowOnError>): RequestResult<Update2Responses, Update2Errors, ThrowOnError> => (options.client ?? client).patch<Update2Responses, Update2Errors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Liveness probe
 *
 * Reports that the process is up. Deliberately touches nothing else, so a database blip
 * cannot convince an orchestrator to restart a perfectly healthy process.
 */
export const live = <ThrowOnError extends boolean = false>(options?: Options<LiveData, ThrowOnError>): RequestResult<LiveResponses, unknown, ThrowOnError> => (options?.client ?? client).get<LiveResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Readiness probe
 *
 * Reports that the process can actually serve traffic, which means reaching the database.
 */
export const ready = <ThrowOnError extends boolean = false>(options?: Options<ReadyData, ThrowOnError>): RequestResult<ReadyResponses, ReadyErrors, ThrowOnError> => (options?.client ?? client).get<ReadyResponses, ReadyErrors, ThrowOnError>({ url: '/health/ready', ...options });
