// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * The password and the refresh token are `SecretString` so that deriving `Debug` on a request
 * body cannot put credentials into a log line.
 */
export type Credentials = {
    email: string;
    password: string;
};

export type DownloadLink = {
    expires_in_seconds: number;
    url: string;
};

export type Health = {
    status: string;
    version: string;
};

export type Item = {
    created_at: string;
    description?: string | null;
    id: string;
    owner_id: string;
    title: string;
    updated_at: string;
};

export type ItemCreate = {
    description?: string | null;
    title: string;
};

/**
 * Every field is optional, so a client can send only what changed. `None` means "leave it
 * alone" rather than "set it to null".
 */
export type ItemUpdate = {
    description?: string | null;
    title?: string | null;
};

export type KeyRequest = {
    key: string;
};

/**
 * A plain acknowledgement, for the handful of endpoints that have nothing to return.
 */
export type Message = {
    message: string;
};

/**
 * OpenAPI has no generics of its own, so each concrete page is named after the type it
 * carries when the document is generated.
 */
export type PageItem = {
    /**
     * Total rows matching the query, not the number returned in `data`.
     */
    count: number;
    data: Array<{
        created_at: string;
        description?: string | null;
        id: string;
        owner_id: string;
        title: string;
        updated_at: string;
    }>;
};

/**
 * OpenAPI has no generics of its own, so each concrete page is named after the type it
 * carries when the document is generated.
 */
export type PageUserPublic = {
    /**
     * Total rows matching the query, not the number returned in `data`.
     */
    count: number;
    data: Array<{
        created_at: string;
        email: string;
        full_name?: string | null;
        id: string;
        is_active: boolean;
        is_superuser: boolean;
    }>;
};

export type Password = string;

export type PasswordUpdate = {
    current_password: Password;
    new_password: Password;
};

/**
 * Problem
 *
 * A problem detail as described by RFC 9457, served as `application/problem+json`. Public
 * so that the OpenAPI document can describe every failure with the shape it really has.
 */
export type Problem = {
    /**
     * A human-readable explanation. Server faults always read "Internal server error", since
     * their detail belongs in the logs rather than in a response.
     */
    detail: string;
    status: number;
    title: string;
};

export type RecoveryRequest = {
    email: string;
};

export type RefreshRequest = {
    refresh_token: string;
};

export type ResetRequest = {
    new_password: Password;
    /**
     * The token from the emailed link.
     */
    token: string;
};

export type TokenPair = {
    access_token: string;
    /**
     * Opaque, single-use, and revocable. Exchanging it invalidates it.
     */
    refresh_token: string;
    token_type: string;
};

/**
 * What the client is about to upload. The name is only used to build a readable key, and the
 * content type is signed into the URL, so both are advisory rather than trusted.
 */
export type UploadRequest = {
    content_type: string;
    filename: string;
};

export type UploadTarget = {
    /**
     * How long the URL is good for.
     */
    expires_in_seconds: number;
    /**
     * Where the file will live. Keep it: this is what you store against your own records.
     */
    key: string;
    /**
     * `PUT` the file here, with the same `Content-Type` that was asked for.
     */
    url: string;
};

/**
 * Creation by a superuser, which may set any field.
 */
export type UserCreate = {
    email: string;
    full_name?: string | null;
    is_active?: boolean;
    is_superuser?: boolean;
    password: Password;
};

export type UserPublic = {
    created_at: string;
    email: string;
    full_name?: string | null;
    id: string;
    is_active: boolean;
    is_superuser: boolean;
};

/**
 * Open registration. Note the absence of `is_active` and `is_superuser`: a self-registered
 * account cannot promote itself, however the request body is shaped.
 */
export type UserRegister = {
    email: string;
    full_name?: string | null;
    password: Password;
};

/**
 * What a superuser may change about anyone, including active status and privileges.
 */
export type UserUpdate = {
    email?: string | null;
    full_name?: string | null;
    is_active?: boolean | null;
    is_superuser?: boolean | null;
    password?: null | Password;
};

/**
 * What a user may change about themselves. Notably not their password, which goes through
 * [`PasswordUpdate`] so that the current one has to be proved.
 */
export type UserUpdateMe = {
    email?: string | null;
    full_name?: string | null;
};

export type ListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * How many rows to step over before the page begins.
         */
        skip?: number;
        /**
         * How many rows the page holds, at most 200.
         */
        limit?: number;
    };
    url: '/api/v1/items';
};

export type ListErrors = {
    401: Problem;
    /**
     * Invalid paging
     */
    422: Problem;
};

export type ListError = ListErrors[keyof ListErrors];

export type ListResponses = {
    200: PageItem;
};

export type ListResponse = ListResponses[keyof ListResponses];

export type CreateData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items';
};

export type CreateErrors = {
    401: Problem;
    422: Problem;
};

export type CreateError = CreateErrors[keyof CreateErrors];

export type CreateResponses = {
    201: Item;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type DeleteData = {
    body?: never;
    path: {
        /**
         * The item to delete
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type DeleteErrors = {
    401: Problem;
    /**
     * No such item, or not yours
     */
    404: Problem;
};

export type DeleteError = DeleteErrors[keyof DeleteErrors];

export type DeleteResponses = {
    200: Message;
};

export type DeleteResponse = DeleteResponses[keyof DeleteResponses];

export type ReadData = {
    body?: never;
    path: {
        /**
         * The item to read
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ReadErrors = {
    401: Problem;
    /**
     * No such item, or not yours
     */
    404: Problem;
};

export type ReadError = ReadErrors[keyof ReadErrors];

export type ReadResponses = {
    200: Item;
};

export type ReadResponse = ReadResponses[keyof ReadResponses];

export type UpdateData = {
    body: ItemUpdate;
    path: {
        /**
         * The item to update
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type UpdateErrors = {
    401: Problem;
    /**
     * No such item, or not yours
     */
    404: Problem;
    422: Problem;
};

export type UpdateError = UpdateErrors[keyof UpdateErrors];

export type UpdateResponses = {
    200: Item;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type AccessTokenData = {
    body: Credentials;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type AccessTokenErrors = {
    /**
     * Unknown address or wrong password
     */
    401: Problem;
    /**
     * The account is deactivated
     */
    403: Problem;
};

export type AccessTokenError = AccessTokenErrors[keyof AccessTokenErrors];

export type AccessTokenResponses = {
    200: TokenPair;
};

export type AccessTokenResponse = AccessTokenResponses[keyof AccessTokenResponses];

export type LogoutData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/login/logout';
};

export type LogoutResponses = {
    200: Message;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LogoutEverywhereData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/logout-everywhere';
};

export type LogoutEverywhereErrors = {
    401: Problem;
};

export type LogoutEverywhereError = LogoutEverywhereErrors[keyof LogoutEverywhereErrors];

export type LogoutEverywhereResponses = {
    200: Message;
};

export type LogoutEverywhereResponse = LogoutEverywhereResponses[keyof LogoutEverywhereResponses];

export type RefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/login/refresh';
};

export type RefreshErrors = {
    /**
     * Unknown, expired, or already used token
     */
    401: Problem;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    200: TokenPair;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type TestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type TestTokenErrors = {
    401: Problem;
};

export type TestTokenError = TestTokenErrors[keyof TestTokenErrors];

export type TestTokenResponses = {
    200: UserPublic;
};

export type TestTokenResponse = TestTokenResponses[keyof TestTokenResponses];

export type RecoverData = {
    body: RecoveryRequest;
    path?: never;
    query?: never;
    url: '/api/v1/password/recover';
};

export type RecoverErrors = {
    422: Problem;
};

export type RecoverError = RecoverErrors[keyof RecoverErrors];

export type RecoverResponses = {
    /**
     * The request was accepted, registered or not
     */
    200: Message;
};

export type RecoverResponse = RecoverResponses[keyof RecoverResponses];

export type ResetData = {
    body: ResetRequest;
    path?: never;
    query?: never;
    url: '/api/v1/password/reset';
};

export type ResetErrors = {
    /**
     * The link is invalid, used, or expired, or the password is too short
     */
    422: Problem;
};

export type ResetError = ResetErrors[keyof ResetErrors];

export type ResetResponses = {
    200: Message;
};

export type ResetResponse = ResetResponses[keyof ResetResponses];

export type Delete2Data = {
    body: KeyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/uploads';
};

export type Delete2Errors = {
    401: Problem;
    404: Problem;
    501: Problem;
};

export type Delete2Error = Delete2Errors[keyof Delete2Errors];

export type Delete2Responses = {
    200: Message;
};

export type Delete2Response = Delete2Responses[keyof Delete2Responses];

export type Create2Data = {
    body: UploadRequest;
    path?: never;
    query?: never;
    url: '/api/v1/uploads';
};

export type Create2Errors = {
    401: Problem;
    422: Problem;
    /**
     * This deployment has no bucket configured
     */
    501: Problem;
};

export type Create2Error = Create2Errors[keyof Create2Errors];

export type Create2Responses = {
    200: UploadTarget;
};

export type Create2Response = Create2Responses[keyof Create2Responses];

export type LinkData = {
    body: KeyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/uploads/link';
};

export type LinkErrors = {
    401: Problem;
    /**
     * No such file, or not yours
     */
    404: Problem;
    501: Problem;
};

export type LinkError = LinkErrors[keyof LinkErrors];

export type LinkResponses = {
    200: DownloadLink;
};

export type LinkResponse = LinkResponses[keyof LinkResponses];

export type List2Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * How many rows to step over before the page begins.
         */
        skip?: number;
        /**
         * How many rows the page holds, at most 200.
         */
        limit?: number;
    };
    url: '/api/v1/users';
};

export type List2Errors = {
    401: Problem;
    /**
     * Not a superuser
     */
    403: Problem;
    /**
     * Invalid paging
     */
    422: Problem;
};

export type List2Error = List2Errors[keyof List2Errors];

export type List2Responses = {
    200: PageUserPublic;
};

export type List2Response = List2Responses[keyof List2Responses];

export type Create3Data = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type Create3Errors = {
    401: Problem;
    /**
     * Not a superuser
     */
    403: Problem;
    /**
     * The address is taken
     */
    409: Problem;
    422: Problem;
};

export type Create3Error = Create3Errors[keyof Create3Errors];

export type Create3Responses = {
    201: UserPublic;
};

export type Create3Response = Create3Responses[keyof Create3Responses];

export type DeleteMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type DeleteMeErrors = {
    401: Problem;
    /**
     * Superusers cannot delete themselves
     */
    403: Problem;
};

export type DeleteMeError = DeleteMeErrors[keyof DeleteMeErrors];

export type DeleteMeResponses = {
    200: Message;
};

export type DeleteMeResponse = DeleteMeResponses[keyof DeleteMeResponses];

export type ReadMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ReadMeErrors = {
    401: Problem;
};

export type ReadMeError = ReadMeErrors[keyof ReadMeErrors];

export type ReadMeResponses = {
    200: UserPublic;
};

export type ReadMeResponse = ReadMeResponses[keyof ReadMeResponses];

export type UpdateMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateMeErrors = {
    401: Problem;
    /**
     * The address is taken
     */
    409: Problem;
    422: Problem;
};

export type UpdateMeError = UpdateMeErrors[keyof UpdateMeErrors];

export type UpdateMeResponses = {
    200: UserPublic;
};

export type UpdateMeResponse = UpdateMeResponses[keyof UpdateMeResponses];

export type UpdateMyPasswordData = {
    body: PasswordUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UpdateMyPasswordErrors = {
    401: Problem;
    /**
     * Wrong current password, or a new one that is unchanged or too short
     */
    422: Problem;
};

export type UpdateMyPasswordError = UpdateMyPasswordErrors[keyof UpdateMyPasswordErrors];

export type UpdateMyPasswordResponses = {
    200: Message;
};

export type UpdateMyPasswordResponse = UpdateMyPasswordResponses[keyof UpdateMyPasswordResponses];

export type SignupData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type SignupErrors = {
    /**
     * The address is taken
     */
    409: Problem;
    422: Problem;
};

export type SignupError = SignupErrors[keyof SignupErrors];

export type SignupResponses = {
    201: UserPublic;
};

export type SignupResponse = SignupResponses[keyof SignupResponses];

export type Delete3Data = {
    body?: never;
    path: {
        /**
         * The user to delete
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type Delete3Errors = {
    401: Problem;
    /**
     * Not a superuser, or deleting yourself
     */
    403: Problem;
    404: Problem;
};

export type Delete3Error = Delete3Errors[keyof Delete3Errors];

export type Delete3Responses = {
    200: Message;
};

export type Delete3Response = Delete3Responses[keyof Delete3Responses];

export type Read2Data = {
    body?: never;
    path: {
        /**
         * The user to read
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type Read2Errors = {
    401: Problem;
    /**
     * Reading someone else without being a superuser
     */
    403: Problem;
    404: Problem;
};

export type Read2Error = Read2Errors[keyof Read2Errors];

export type Read2Responses = {
    200: UserPublic;
};

export type Read2Response = Read2Responses[keyof Read2Responses];

export type Update2Data = {
    body: UserUpdate;
    path: {
        /**
         * The user to update
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type Update2Errors = {
    401: Problem;
    /**
     * Not a superuser
     */
    403: Problem;
    404: Problem;
    /**
     * The address is taken
     */
    409: Problem;
    422: Problem;
};

export type Update2Error = Update2Errors[keyof Update2Errors];

export type Update2Responses = {
    200: UserPublic;
};

export type Update2Response = Update2Responses[keyof Update2Responses];

export type LiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type LiveResponses = {
    200: Health;
};

export type LiveResponse = LiveResponses[keyof LiveResponses];

export type ReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ReadyErrors = {
    /**
     * The database is unreachable
     */
    500: Problem;
};

export type ReadyError = ReadyErrors[keyof ReadyErrors];

export type ReadyResponses = {
    200: Health;
};

export type ReadyResponse = ReadyResponses[keyof ReadyResponses];
