// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * The password and the refresh token are `SecretString` so that deriving `Debug` on a request
 * body cannot put credentials into a log line.
 */
export const zCredentials = z.object({
    email: z.email(),
    password: z.string()
});

export const zDownloadLink = z.object({
    expires_in_seconds: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    url: z.string()
});

export const zHealth = z.object({
    status: z.string(),
    version: z.string()
});

export const zItem = z.object({
    created_at: z.iso.datetime(),
    description: z.string().nullish(),
    id: z.uuid(),
    owner_id: z.uuid(),
    title: z.string(),
    updated_at: z.iso.datetime()
});

export const zItemCreate = z.object({
    description: z.string().max(4096).nullish(),
    title: z.string().min(1).max(255)
});

/**
 * Every field is optional, so a client can send only what changed. `None` means "leave it
 * alone" rather than "set it to null".
 */
export const zItemUpdate = z.object({
    description: z.string().max(4096).nullish(),
    title: z.string().min(1).max(255).nullish()
});

export const zKeyRequest = z.object({
    key: z.string()
});

/**
 * A plain acknowledgement, for the handful of endpoints that have nothing to return.
 */
export const zMessage = z.object({
    message: z.string()
});

/**
 * OpenAPI has no generics of its own, so each concrete page is named after the type it
 * carries when the document is generated.
 */
export const zPageItem = z.object({
    count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    data: z.array(z.object({
        created_at: z.iso.datetime(),
        description: z.string().nullish(),
        id: z.uuid(),
        owner_id: z.uuid(),
        title: z.string(),
        updated_at: z.iso.datetime()
    }))
});

/**
 * OpenAPI has no generics of its own, so each concrete page is named after the type it
 * carries when the document is generated.
 */
export const zPageUserPublic = z.object({
    count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    data: z.array(z.object({
        created_at: z.iso.datetime(),
        email: z.string(),
        full_name: z.string().nullish(),
        id: z.uuid(),
        is_active: z.boolean(),
        is_superuser: z.boolean()
    }))
});

export const zPassword = z.string().min(8).max(128);

export const zPasswordUpdate = z.object({
    current_password: zPassword,
    new_password: zPassword
});

/**
 * Problem
 *
 * A problem detail as described by RFC 9457, served as `application/problem+json`. Public
 * so that the OpenAPI document can describe every failure with the shape it really has.
 */
export const zProblem = z.object({
    detail: z.string(),
    status: z.int().gte(0).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    title: z.string()
});

export const zRecoveryRequest = z.object({
    email: z.email()
});

export const zRefreshRequest = z.object({
    refresh_token: z.string()
});

export const zResetRequest = z.object({
    new_password: zPassword,
    token: z.string()
});

export const zTokenPair = z.object({
    access_token: z.string(),
    refresh_token: z.string(),
    token_type: z.string()
});

/**
 * What the client is about to upload. The name is only used to build a readable key, and the
 * content type is signed into the URL, so both are advisory rather than trusted.
 */
export const zUploadRequest = z.object({
    content_type: z.string(),
    filename: z.string()
});

export const zUploadTarget = z.object({
    expires_in_seconds: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    key: z.string(),
    url: z.string()
});

/**
 * Creation by a superuser, which may set any field.
 */
export const zUserCreate = z.object({
    email: z.email(),
    full_name: z.string().nullish(),
    is_active: z.boolean().optional(),
    is_superuser: z.boolean().optional(),
    password: zPassword
});

export const zUserPublic = z.object({
    created_at: z.iso.datetime(),
    email: z.string(),
    full_name: z.string().nullish(),
    id: z.uuid(),
    is_active: z.boolean(),
    is_superuser: z.boolean()
});

/**
 * Open registration. Note the absence of `is_active` and `is_superuser`: a self-registered
 * account cannot promote itself, however the request body is shaped.
 */
export const zUserRegister = z.object({
    email: z.email(),
    full_name: z.string().nullish(),
    password: zPassword
});

/**
 * What a superuser may change about anyone, including active status and privileges.
 */
export const zUserUpdate = z.object({
    email: z.email().nullish(),
    full_name: z.string().nullish(),
    is_active: z.boolean().nullish(),
    is_superuser: z.boolean().nullish(),
    password: zPassword.nullish()
});

/**
 * What a user may change about themselves. Notably not their password, which goes through
 * [`PasswordUpdate`] so that the current one has to be proved.
 */
export const zUserUpdateMe = z.object({
    email: z.email().nullish(),
    full_name: z.string().nullish()
});

export const zListQuery = z.object({
    skip: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional().default(BigInt(0)),
    limit: z.coerce.bigint().gte(BigInt(1)).lte(BigInt(200)).optional().default(BigInt(20))
});

export const zListResponse = zPageItem;

export const zCreateBody = zItemCreate;

export const zCreateResponse = zItem;

export const zDeletePath = z.object({
    id: z.uuid()
});

export const zDeleteResponse = zMessage;

export const zReadPath = z.object({
    id: z.uuid()
});

export const zReadResponse = zItem;

export const zUpdateBody = zItemUpdate;

export const zUpdatePath = z.object({
    id: z.uuid()
});

export const zUpdateResponse = zItem;

export const zAccessTokenBody = zCredentials;

export const zAccessTokenResponse = zTokenPair;

export const zLogoutBody = zRefreshRequest;

export const zLogoutResponse = zMessage;

export const zLogoutEverywhereResponse = zMessage;

export const zRefreshBody = zRefreshRequest;

export const zRefreshResponse = zTokenPair;

export const zTestTokenResponse = zUserPublic;

export const zRecoverBody = zRecoveryRequest;

/**
 * The request was accepted, registered or not
 */
export const zRecoverResponse = zMessage;

export const zResetBody = zResetRequest;

export const zResetResponse = zMessage;

export const zDelete2Body = zKeyRequest;

export const zDelete2Response = zMessage;

export const zCreate2Body = zUploadRequest;

export const zCreate2Response = zUploadTarget;

export const zLinkBody = zKeyRequest;

export const zLinkResponse = zDownloadLink;

export const zList2Query = z.object({
    skip: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional().default(BigInt(0)),
    limit: z.coerce.bigint().gte(BigInt(1)).lte(BigInt(200)).optional().default(BigInt(20))
});

export const zList2Response = zPageUserPublic;

export const zCreate3Body = zUserCreate;

export const zCreate3Response = zUserPublic;

export const zDeleteMeResponse = zMessage;

export const zReadMeResponse = zUserPublic;

export const zUpdateMeBody = zUserUpdateMe;

export const zUpdateMeResponse = zUserPublic;

export const zUpdateMyPasswordBody = zPasswordUpdate;

export const zUpdateMyPasswordResponse = zMessage;

export const zSignupBody = zUserRegister;

export const zSignupResponse = zUserPublic;

export const zDelete3Path = z.object({
    id: z.uuid()
});

export const zDelete3Response = zMessage;

export const zRead2Path = z.object({
    id: z.uuid()
});

export const zRead2Response = zUserPublic;

export const zUpdate2Body = zUserUpdate;

export const zUpdate2Path = z.object({
    id: z.uuid()
});

export const zUpdate2Response = zUserPublic;

export const zLiveResponse = zHealth;

export const zReadyResponse = zHealth;
